version: '3'
services:
    apache:
        build: .docker/apache
        container_name: corporalabs_apache
        ports:
          - 8081:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/www/corporalabs
        depends_on:
          - php

    mysql:
        image: mysql:8
        container_name: corporalabs_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        ports:
            - 3308:3306
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"        
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: corporalabs
            MYSQL_USER: corporaadmin
            MYSQL_PASSWORD: password

    php:
        build: .docker/php
        container_name: corporalabs_php
        volumes:
          - .:/home/www/corporalabs
        depends_on:
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: corporalabs_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8282:80
        links:
            - mysql
